[cdn]
	build_command = "npm run build"
	build_output = "dist/"
	site_id = "xxxx"

[matchmaker]
	tier = "basic-1d1"
	max_players = 16

	[matchmaker.docker]
		dockerfile = "Dockerfile"
		# or
		image = "test"
		image_id = "xxxx"
		env = { PORT = "80" }
		args = []

	[matchmaker.ports]
		default = { proto = "https", target = 80 }

	[matchmaker.game_modes]
		default = {}

[kv]

