[cdn]
	build_command = "npm run build"
	build_output = "dist"

[matchmaker]
	max_players = 32
	tier = "basic-1d1"

[matchmaker.regions]
	lnd-sfo = {}
	lnd-fra = {}

[matchmaker.docker]
	dockerfile = "Dockerfile"

[matchmaker.game_modes]
	default = {}

[kv]

[identity]

