[package]
name = "rivetctl"
version = "0.0.1"
authors = ["Nathan Flurry <developer@nathanflurry.com>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2.16", features = ["derive", "env"] }
futures-util = "0.3"
humansize = "1.1"
ignore = "0.4"
mime_guess = "2.0"
rand = "0.8"
reqwest = { version = "0.11", features = ["stream"] }
rivetctl = { path = "../rivetctl", package = "rivetctl-lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.2"
tokio = { version = "1.6", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }

