[package]
name = "rivet"
version = "0.0.48"
authors = ["Rivet Gaming, Inc. <developer@rivet.gg>"]
edition = "2018"
license = "MIT"
build = "build.rs"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.3"
aws-smithy-types = "*"
chrono = "0.4.21"
clap = { version = "3.2.16", features = ["derive", "env"] }
cli-core = { path = "../core", package = "rivet-cli-core" }
config = "0.13.2"
console = "0.15"
futures-util = "0.3"
humansize = "1.1"
ignore = "0.4"
mime_guess = "2.0"
rand = "0.8"
reqwest = { version = "0.11", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabled = "0.8.0"
tempfile = "3.2"
term_size = "0.3.2"
tokio = { version = "1.6", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
uuid = { version = "1.3", features = ["v4"] }
webbrowser = "0.8.7"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "7.5", default_features = false, features = ["build", "git", "rustc", "cargo"] }

