name: Deploy to Rivet

on:
  push:
    branches:
      - '**'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    outputs:
      ns_name: ${{ steps.derive_names.outputs.ns_name }}
      version_name: ${{ steps.derive_names.outputs.version_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate ns_name and version_name
        id: derive_names
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          ns_name=$(echo $branch_name | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z-]//g')
          short_hash=$(git rev-parse --short HEAD)
          version_name="${short_hash} (${ns_name})"
          echo "::set-output name=ns_name::$ns_name"
          echo "::set-output name=version_name::$version_name"

