# How Rivet CDN should host your static assets on our CDN.
#
# https://docs.rivet.gg/cdn/introduction
[cdn]
	# Command to run before uploading the site to Rivet. This can be used to
	# build any JavaScript bundles or generate assets.
	build_command = "__BUILD_COMMAND__"

	# The folder to upload to Rivet.
	#
	# If you're hosting a website, ensure that `index.html` is in the root of
	# this folder.
	build_output = "__BUILD_OUTPUT__"

