# === Rivet Version Configuration ===
# 
# - More info: https://docs.rivet.gg/general/concepts/rivet-version-config
# - Reference: https://docs.rivet.gg/cloud/api/post-games-versions#body
# - Publish a new version with `rivet publish`
#

