# === Rivet Configuration ===
# 
# - More info: https://rivet.gg/docs/general/concepts/version-config
# - Reference: https://rivet.gg/docs/cloud/api/games/versions/create-game-version
# - Publish a new version with `rivet publish`
#
