# === Rivet Version Configuration ===
# 
# - More info: https://rivet.gg/docs/general/concepts/rivet-version-config
# - Reference: https://rivet.gg/docs/cloud/api/post-games-versions#body
# - Publish a new version with `rivet publish`
#

