# === Rivet Configuration ===
# 
# - More info: https://rivet.gg/docs/general/concepts/version-config
# - Reference: https://rivet.gg/docs/cloud/api/games/versions/create-game-version
# - Publish a new version with `rivet publish`
#

engine:
  unreal:
    game_module: __GAME_MODULE__

# How the game lobbies run and how players connect to the game.
#
# https://rivet.gg/docs/matchmaker
matchmaker:
  # How many players can join a specific lobby.
  #
  # Read more about matchmaking: https://rivet.gg/docs/matchmaker/concepts/finding-lobby
  max_players: 32

  # The hardware to provide for lobbies.
  #
  # Available tiers: https://rivet.gg/docs/dynamic-servers/concepts/available-tiers
  tier: basic-1d1

  # What game modes are available.
  #
  # Properties like `max_players`, `tier`, `dockerfile`, `regions`, and more can
  # be overridden for specific game modes.
  game_modes:
    default: {}

  # Runtime configuration for running the Unreal game server.
  docker:
    dockerfile: server.debug.Dockerfile
    ports:
      default:
        port: 7777
        protocol: udp

