# === Rivet Version Configuration ===
# 
# - More info: https://docs.rivet.gg/general/concepts/rivet-version-config
# - Reference: https://docs.rivet.gg/cloud/api/post-games-versions#body
# - Publish a new version with `rivet publish`
#

[engine.unreal]
    game_module = "__MODULE_NAME__"

# How the game lobbies run and how players connect to the game.
#
# https://docs.rivet.gg/matchmaker/introduction
[matchmaker]
	# How many players can join a specific lobby.
	#
	# Read more about matchmaking: https://docs.rivet.gg/matchmaker/concepts/finding-lobby
	max_players = 32

	# The hardware to provide for lobbies.
	#
	# Available tiers: https://docs.rivet.gg/serverless-lobbies/concepts/available-tiers
	tier = "basic-1d1"

# What game modes are avaiable.
#
# Properties like `max_players`, `tier`, `dockerfile`, `regions`, and more can
# be overriden for specific game modes.
[matchmaker.game_modes]
	default = {}

# Which regions the game should be available in.
#
# Available regions: https://docs.rivet.gg/serverless-lobbies/concepts/available-regions
[matchmaker.regions]
	lnd-sfo = {}
	lnd-fra = {}
