name: Rename

permissions:
  contents: write

on: 
  push:
    branches:
      - main

jobs:
  update_issue_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Find and update issue labels
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo
            const oldLabel = 'autorelease: pending'
            const newLabel = 'autorelease: tagged'

            const issues = await github.rest.search.issuesAndPullRequests({
              q: `repo:${owner}/${repo} is:open label:"${oldLabel}"`,
              per_page: 100
            })

            for (const issue of issues.data.items) {
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issue.number,
                labels: issue.labels
                  .map(label => label.name)
                  .filter(labelName => labelName !== oldLabel)
                  .concat(newLabel)
              })
            }