name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, [windows, self-hosted], macos-12]
    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew
        if: startsWith(matrix.os, 'macos-')
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install Docker
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install docker
          colima start

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # We use a globally installed version of Rust
      - name: Update env
        if: contains(matrix.os, 'windows')
        run: |
          Add-Content $env:GITHUB_PATH "C:\Rust\.cargo\bin"

      # - name: Test 2
      #   if: contains(matrix.os, 'windows')
      #   run: |
      #     $env:PATH
      #     $env:GITHUB_PATH
      #     rustup

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        env:
          RUSTUP_HOME: C:\Rust\rustup
          CARGO_HOME: C:\Rust\cargo
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          RIVET_API_ENDPOINT: ${{ secrets.RIVET_API_ENDPOINT }}
          RIVET_TOKEN: ${{ secrets.RIVET_TOKEN }}
          RUST_BACKTRACE: 1
        with:
          command: test
