name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, [windows, self-hosted], macos-12]
    steps:
      # Needs to be done before checkout because of git
      - name: Update env
        if: contains(matrix.os, 'windows')
        run: |
          Add-Content $env:GITHUB_PATH "C:\Rust\.cargo\bin"
          Add-Content $env:GITHUB_PATH "C:\Strawberry\c\bin"
          Add-Content $env:GITHUB_PATH "C:\Strawberry\perl\site\bin"
          Add-Content $env:GITHUB_PATH "C:\Strawberry\perl\bin"
          Add-Content $env:GITHUB_PATH "C:\Program Files\Git\cmd"

      # - name: Fix git file issues
      #   if: contains(matrix.os, 'windows')
      #   run: |
      #     git config --global --add safe.directory C:/actions-runner/_work/cli/cli

      - uses: actions/checkout@v4

      - name: Install Homebrew
        if: startsWith(matrix.os, 'macos-')
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install Docker
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install docker
          colima start

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust (Windows)
        uses: actions-rs/toolchain@v1
        if: contains(matrix.os, 'windows')
        env:
          RUSTUP_HOME: C:\Rust\.rustup
          CARGO_HOME: C:\Rust\.cargo
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        if: |
          !contains(matrix.os, 'windows')
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          RIVET_API_ENDPOINT: ${{ secrets.RIVET_API_ENDPOINT }}
          RIVET_TOKEN: ${{ secrets.RIVET_TOKEN }}
          RUST_BACKTRACE: 1
          CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG: true
        with:
          command: test
