name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew
        if: startsWith(matrix.os, 'macos-')
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install Docker
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install docker
          colima start

      - name: Switch to Windows Containers
        if: startsWith(matrix.os, 'windows-')
        run: |
          "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchWindowsEngine

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          RIVET_API_ENDPOINT: ${{ secrets.RIVET_API_ENDPOINT }}
          RIVET_TOKEN: ${{ secrets.RIVET_TOKEN }}
          RUST_BACKTRACE: 1
        with:
          command: test
